// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'Templates\Registry\Csharp\SemanticConventionsMetrics.cs.j2' </auto-generated>

#nullable enable

using System.Diagnostics.Metrics;

namespace Shared;

/// <summary>
/// Metric instrument definitions for the FPCC service.
/// </summary>
public static class FpccMetrics
{
    /// <summary>
    /// The name of the meter. Use this value to register the meter with OpenTelemetry via <c>AddMeter</c>.
    /// </summary>
    public const string MeterName = "FPCC";

    private static readonly Meter s_meter = new(MeterName, "1.0.0");

    /// <summary>
    /// Duration of the FraudForce risk assessment check.
    /// </summary>
    /// <remarks>
    /// Measures latency of the fraud scoring operation.
    /// </remarks>
    public static readonly Histogram<double> FpccFraudforceDuration =
        s_meter.CreateHistogram<double>("fpcc.fraudforce.duration", "ms", "Duration of the FraudForce risk assessment check.");

    /// <summary>
    /// Distribution of fraud risk scores returned by the FraudForce engine.
    /// </summary>
    /// <remarks>
    /// Scores typically range from -10 (high risk) to 10 (low risk).
    /// </remarks>
    public static readonly Histogram<double> FpccFraudforceScore =
        s_meter.CreateHistogram<double>("fpcc.fraudforce.score", "{score}", "Distribution of fraud risk scores returned by the FraudForce engine.");

    /// <summary>
    /// Duration of the confirm-withdrawal HTTP call to PAM.
    /// </summary>
    /// <remarks>
    /// Measures the round-trip latency of the POST api/Withdrawals/Confirm call.
    /// </remarks>
    public static readonly Histogram<double> FpccWithdrawalConfirmDuration =
        s_meter.CreateHistogram<double>("fpcc.withdrawal.confirm.duration", "ms", "Duration of the confirm-withdrawal HTTP call to PAM.");

    /// <summary>
    /// Total failed confirm-withdrawal HTTP calls to PAM.
    /// </summary>
    /// <remarks>
    /// Increment on HTTP errors or exceptions when calling the PAM Confirm endpoint. Alert if rate > 0.
    /// </remarks>
    public static readonly Counter<long> FpccWithdrawalConfirmError =
        s_meter.CreateCounter<long>("fpcc.withdrawal.confirm.error", "errors", "Total failed confirm-withdrawal HTTP calls to PAM.");

    /// <summary>
    /// Total withdrawals processed by FPCC.
    /// </summary>
    /// <remarks>
    /// Tagged by status (success/failure) to enable error-rate alerting.
    /// </remarks>
    public static readonly Counter<long> FpccWithdrawalProcessed =
        s_meter.CreateCounter<long>("fpcc.withdrawal.processed", "withdrawals", "Total withdrawals processed by FPCC.");

    /// <summary>
    /// Duration of withdrawal processing in FPCC.
    /// </summary>
    /// <remarks>
    /// Measures end-to-end time from message receipt to completion, including FraudForce and confirm call.
    /// </remarks>
    public static readonly Histogram<double> FpccWithdrawalProcessingDuration =
        s_meter.CreateHistogram<double>("fpcc.withdrawal.processing.duration", "ms", "Duration of withdrawal processing in FPCC.");
}

