// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'Templates\Registry\Csharp\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace Shared;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class FpccAttributes
{
    /// <summary>
    /// The fraud risk score returned by the FraudForce engine.
    /// </summary>
    /// <remarks>
    /// A negative score indicates higher risk. Typically ranges from -10 to 10.
    /// </remarks>
    public const string FpccFraudforceScore = "fpcc.fraudforce.score";

    /// <summary>
    /// The account identifier associated with the withdrawal.
    /// </summary>
    /// <remarks>
    /// This is the unique ID of the account from which funds are withdrawn.
    /// </remarks>
    public const string FpccWithdrawalAccountId = "fpcc.withdrawal.account_id";

    /// <summary>
    /// The monetary amount of the withdrawal.
    /// </summary>
    /// <remarks>
    /// The amount requested for withdrawal, in the account's currency.
    /// </remarks>
    public const string FpccWithdrawalAmount = "fpcc.withdrawal.amount";

    /// <summary>
    /// The unique identifier of the withdrawal.
    /// </summary>
    /// <remarks>
    /// This is the system-generated withdrawal ID.
    /// </remarks>
    public const string FpccWithdrawalId = "fpcc.withdrawal.id";
}