// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'Templates\Registry\Csharp\SemanticConventionsAttributes.cs.j2' </auto-generated>

#nullable enable

#pragma warning disable CS1570 // XML comment has badly formed XML

namespace Shared;

/// <summary>
/// Constants for semantic attribute names outlined by the OpenTelemetry specifications.
/// </summary>
public static class PamAttributes
{
    /// <summary>
    /// The account identifier associated with the withdrawal.
    /// </summary>
    /// <remarks>
    /// This is the unique ID of the account from which funds are withdrawn.
    /// </remarks>
    public const string PamWithdrawalAccountId = "pam.withdrawal.account_id";

    /// <summary>
    /// The monetary amount of the withdrawal.
    /// </summary>
    /// <remarks>
    /// The amount requested for withdrawal, in the account's currency.
    /// </remarks>
    public const string PamWithdrawalAmount = "pam.withdrawal.amount";

    /// <summary>
    /// The IBAN of the account associated with the withdrawal.
    /// </summary>
    /// <remarks>
    /// This is the International Bank Account Number for the account from which funds are withdrawn.
    /// </remarks>
    public const string PamWithdrawalIban = "pam.withdrawal.iban";

    /// <summary>
    /// The unique identifier of the withdrawal.
    /// </summary>
    /// <remarks>
    /// This is the system-generated withdrawal ID.
    /// </remarks>
    public const string PamWithdrawalId = "pam.withdrawal.id";
}