// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// <auto-generated>This file has been auto generated from 'Templates\Registry\Csharp\SemanticConventionsMetrics.cs.j2' </auto-generated>

#nullable enable

using System.Diagnostics.Metrics;

namespace Shared;

/// <summary>
/// Metric instrument definitions for the PAM service.
/// </summary>
public static class PamMetrics
{
    /// <summary>
    /// The name of the meter. Use this value to register the meter with OpenTelemetry via <c>AddMeter</c>.
    /// </summary>
    public const string MeterName = "PAM";

    private static readonly Meter s_meter = new(MeterName, "1.0.0");

    /// <summary>
    /// Distribution of withdrawal amounts.
    /// </summary>
    /// <remarks>
    /// Records the monetary amount of each withdrawal for percentile analysis and anomaly detection.
    /// </remarks>
    public static readonly Histogram<double> PamWithdrawalAmount =
        s_meter.CreateHistogram<double>("pam.withdrawal.amount", "{currency}", "Distribution of withdrawal amounts.");

    /// <summary>
    /// Total withdrawals confirmed via the PAM API.
    /// </summary>
    /// <remarks>
    /// Incremented when FPCC calls back to confirm a withdrawal has been processed.
    /// </remarks>
    public static readonly Counter<long> PamWithdrawalConfirmed =
        s_meter.CreateCounter<long>("pam.withdrawal.confirmed", "withdrawals", "Total withdrawals confirmed via the PAM API.");

    /// <summary>
    /// Duration of the Initiate withdrawal flow in PAM.
    /// </summary>
    /// <remarks>
    /// Measures end-to-end time of the Initiate operation including DB writes and Service Bus publish.
    /// </remarks>
    public static readonly Histogram<double> PamWithdrawalInitiateDuration =
        s_meter.CreateHistogram<double>("pam.withdrawal.initiate.duration", "ms", "Duration of the Initiate withdrawal flow in PAM.");

    /// <summary>
    /// Total withdrawals initiated via the PAM API.
    /// </summary>
    /// <remarks>
    /// Incremented when a new withdrawal request is successfully processed and published to Service Bus.
    /// </remarks>
    public static readonly Counter<long> PamWithdrawalInitiated =
        s_meter.CreateCounter<long>("pam.withdrawal.initiated", "withdrawals", "Total withdrawals initiated via the PAM API.");
}

