@PAM_HostAddress = https://localhost:7292


###
### basic example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 1,
  "amount": 1.00,
  "withdrawalId": 1
}

###
### basic span example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 2,
  "amount": 2.00,
  "withdrawalId": 12
}

###

###
### basic new root span example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 3,
  "amount": 3.00,
  "withdrawalId": 123
}

###

###
### advanced span example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 4,
  "amount": 4.00,
  "withdrawalId": 1234
}

###

###
### advanced span no stop example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 5,
  "amount": 5.00,
  "withdrawalId": 12345
}

###


###
### advanced new root span example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 6,
  "amount": 6.00,
  "withdrawalId": 123456
}

###

###
### slower request example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 7,
  "amount": 7.00,
  "withdrawalId": 1234567
}

###

###
### exception FPCC example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 8,
  "amount": 8.00,
  "withdrawalId": 12345678
}

###

###
### exception PAM example
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 9,
  "amount": 9.00,
  "withdrawalId": 123456789
}

###

