@PAM_HostAddress = https://localhost:7292


###
### Publish a withdrawal message to Service Bus
POST {{PAM_HostAddress}}/api/Withdrawals/Initiate
Content-Type: application/json

{
  "accountId": 1,
  "amount": 100.00,
  "withdrawalId": 12345
}

###

